config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  resource :playlists
  root to: "home#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :omniauthable, omniauth_providers: %i[spotify]

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]
      user.name = auth.info.name
      info = auth.to_hash
      user.spotify_info = info.to_json
      # assuming the user model has a name
      #user.image = auth.info.image # assuming the user model has an image
      # If you are using confirmable and the provider(s) you use validate emails,
      # uncomment the line below to skip the confirmation emails.
      # user.skip_confirmation!
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/playlists_controller.rb
class PlaylistsController < ApplicationController
  def new
  end

  def create
    spotify_user = RSpotify::User.new(JSON.parse(current_user.spotify_info))
    playlist = spotify_user.create_playlist!(params[:name])
  end

  def playlist_params
    params.require(:playlist).permit(:name)
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def spotify
     # You need to implement the method below in your model (e.g. app/models/user.rb)
     @user = User.from_omniauth(request.env["omniauth.auth"])

     if @user.persisted?
       sign_in_and_redirect @user, event: :authentication #this will throw if @user is not activated
       set_flash_message(:notice, :success, kind: "Spotify") if is_navigational_format?
     else
       session["devise.spotify_data"] = request.env["omniauth.auth"]
       redirect_to new_user_registration_url
     end
   end

   def failure
     redirect_to root_path
   end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/index.slim
ul.square-menu
  li
    = link_to "Search track",   '#'
  li
    = link_to "Crate a playlist",   'playlists/new'
  li
    = link_to "Play random music", '#'
  li
    = link_to "Discover new music", '#'
  li
    = link_to "Search Artist", '#'

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SpotifyApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <% if user_signed_in? %>
      Welcome, <%= current_user.email %>
      <%= link_to "Logout", destroy_user_session_path, method: :delete %>
    <% else %>
      <%= link_to "Sign in", new_user_session_path %>
      <%= link_to "Sign in with Spotify", user_spotify_omniauth_authorize_path %>
    <% end %>

    <%= yield %>
  </body>
</html>

app/views/playlists/new.slim
= form_tag playlists_path, method: :post do |f|
  div.field
    = text_field_tag :name
  div.actions
    = submit_tag :create